-- Fix HSE-IT questions: correct dimension keys and question texts
TRUNCATE survey.survey_questions;

INSERT INTO survey.survey_questions (question_number, dimension, question_text) VALUES
(1,  'cargo',                'Eu sei exatamente o que é esperado de mim no trabalho'),
(2,  'controle',             'Posso decidir quando fazer uma pausa'),
(3,  'demandas',             'Diferentes grupos no trabalho exigem coisas de mim que são difíceis de combinar'),
(4,  'cargo',                'Eu sei como fazer meu trabalho'),
(5,  'relacionamentos',      'Estou sujeito(a) a atenção pessoal ou assédio na forma de palavras ou comportamentos ofensivos'),
(6,  'demandas',             'Tenho prazos inatingíveis'),
(7,  'apoio_colegas',        'Se o trabalho fica difícil, meus colegas me ajudam'),
(8,  'apoio_chefia',         'Sou apoiado(a) em uma crise emocional no trabalho'),
(9,  'demandas',             'Tenho que trabalhar muito intensamente'),
(10, 'controle',             'Tenho voz nas mudanças no modo como faço meu trabalho'),
(11, 'cargo',                'Tenho tempo suficiente para completar meu trabalho'),
(12, 'demandas',             'Tenho que desconsiderar regras ou procedimentos para fazer o trabalho'),
(13, 'cargo',                'Sei qual é o meu papel e responsabilidades'),
(14, 'relacionamentos',      'Tenho que trabalhar com pessoas que têm valores de trabalho diferentes'),
(15, 'controle',             'Posso planejar quando fazer as pausas'),
(16, 'demandas',             'Tenho volume de trabalho pesado'),
(17, 'cargo',                'Existe uma boa combinação entre o que a organização espera de mim e as habilidades que tenho'),
(18, 'demandas',             'Tenho que trabalhar muito rapidamente'),
(19, 'controle',             'Tenho uma palavra a dizer sobre o ritmo em que trabalho'),
(20, 'demandas',             'Tenho que negligenciar alguns aspectos do meu trabalho porque tenho muito a fazer'),
(21, 'relacionamentos',      'Existe fricção ou raiva entre colegas'),
(22, 'demandas',             'Não tenho tempo para fazer uma pausa'),
(23, 'apoio_chefia',         'Minha chefia imediata me encoraja no trabalho'),
(24, 'apoio_colegas',        'Recebo o respeito no trabalho que mereço de meus colegas'),
(25, 'controle',             'Tenho controle sobre quando fazer uma pausa'),
(26, 'comunicacao_mudancas', 'Os funcionários são sempre consultados sobre mudanças no trabalho'),
(27, 'apoio_colegas',        'Posso contar com meus colegas para me ajudar quando as coisas ficam difíceis no trabalho'),
(28, 'comunicacao_mudancas', 'Posso conversar com minha chefia sobre algo que me incomodou'),
(29, 'apoio_chefia',         'Minha chefia me apoia para o trabalho'),
(30, 'controle',             'Tenho alguma participação em decisões sobre o meu trabalho'),
(31, 'apoio_colegas',        'Recebo ajuda e apoio de meus colegas'),
(32, 'comunicacao_mudancas', 'Quando ocorrem mudanças no trabalho, tenho clareza sobre como funcionará na prática'),
(33, 'apoio_chefia',         'Recebo feedback sobre o meu trabalho'),
(34, 'relacionamentos',      'Existe tensão entre mim e colegas de trabalho'),
(35, 'apoio_chefia',         'Minha chefia me incentiva nas minhas atividades');
